version: "0.1"
services:
  db:
  image: postgres:18-alpine
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB: db
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: pass

  migrations:

  java:
    depends_on:
      - db