spring.application.name=bulletin-board-java

# Настройки JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Драйвер
spring.datasource.driver-class-name=org.postgresql.Driver

# URL базы данных
spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}

# Логин и пароль
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}